---
name: Pr치ctica negaci칩n y cuantificaci칩n
locale: es
type: practice
beta: false
teacher_info: |-
  La idea es practicar

  * cuantificador existencial
  * cuantificador universal
  * negaci칩n
language: prolog
id_format: "%05d"
order:
- 30
- 40
- 3
- 6
- 70
- 71
- 72
- 73
- 74
