---
name: Práctica negación y cuantificación
locale: es
type: practice
beta: false
teacher_info: |-
  La idea es practicar

  * cuantificador existencial
  * cuantificador universal
  * negación
  * artimética
language: prolog
id_format: '%05d'
order:
- 30
- 40
- 3
- 50
- 6
- 70
- 71
